version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:9.6.1
    steps:
      - checkout
      - run: echo "hello world"



# Config walk through
# following a project on CircleCI
# jobs: hello world
# https://circleci.com/gh/annapamma/sandbox/228
# workflows: build - then test
# https://circleci.com/workflow-run/776f8602-281f-42a2-a2a7-fd443c77f444
# caching dependencies
# before: https://circleci.com/gh/annapamma/sandbox/178
# after: https://circleci.com/gh/annapamma/sandbox/231
# parallel: timing data
# https://circleci.com/gh/annapamma/sandbox/234
# https://github.com/annapamma/spring-petclinic
# https://circleci.com/gh/annapamma/spring-petclinic/145#build-timing/containers/0/actions/102

